library(terra)
# Helper function to create test data
create_test_data_plot <- function(n = 20, has_outliers = FALSE, type = "sf") {
  set.seed(123)
  data <- data.frame(
    x = rnorm(n),
    y = rnorm(n)
  )
  
  if(has_outliers){
    data$out_spatial <- sample(c(TRUE, FALSE), n, replace = TRUE, prob = c(0.2, 0.8))
    data$out_env <- sample(c(TRUE, FALSE), n, replace = TRUE, prob = c(0.1, 0.9))
  }
  if (type == "sf") {
    if(requireNamespace("sf", quietly = TRUE)){
      sf_data <- sf::st_as_sf(data, coords = c("x", "y"), crs = 4326)
      return(sf_data)
    } else {
      stop("The package sf is required to generate sf data")
    }
    
  } else {
    return(data)
  }
}

create_test_raster <- function(extent = c(-10, 10, -10, 10), resolution = 1){
  r <- terra::rast(terra::ext(extent), resolution = resolution, crs = "EPSG:4326")
  terra::values(r) <- runif(terra::ncell(r))
  return(r)
}

create_test_shape <- function(extent = c(-5, 5, -5, 5)){
  if(requireNamespace("sf", quietly = TRUE)){
    poly <- sf::st_polygon(list(matrix(c(extent[1], extent[3],
                                         extent[2], extent[3],
                                         extent[2], extent[4],
                                         extent[1], extent[4],
                                         extent[1], extent[3]), ncol = 2, byrow = TRUE)))
    
    shape <- sf::st_sf(geometry = sf::st_sfc(poly), crs = 4326)
    return(shape)
  } else {
    stop("The package sf is required to generate sf data")
  }
}


test_that("plotOutliers input validation", {
  # Invalid 'pres'
  expect_error(plotOutliers(pres = "not_a_sf"),
               "pres must be an sf object with POINT geometry")
  
  # Invalid 'pres' sf geometry
  if(requireNamespace("sf", quietly = TRUE)){
    non_point_sf <- sf::st_sf(sf::st_sfc(sf::st_linestring(matrix(c(0,0,1,1),ncol = 2, byrow = TRUE))))
    expect_error(plotOutliers(pres = non_point_sf),
                 "pres must be an sf object with POINT geometry")
  }
  
  # Invalid 'r'
  sf_data <- create_test_data_plot(has_outliers = TRUE)
  expect_error(plotOutliers(pres = sf_data, r = "not_a_raster"),
               "r must be a terra::SpatRaster object")
  
  # Invalid shpToPlot
  r <- create_test_raster()
  expect_error(plotOutliers(pres = sf_data, r = r, shpToPlot = "not_a_sf"),
               "shpToPlot must be an sf object")
  
  # Shapefile and presence data with different CRS
  if(requireNamespace("sf", quietly = TRUE)){
    shp <- create_test_shape()
    different_crs_shp <- sf::st_transform(shp, 32617)
    
    expect_warning(plotOutliers(pres = sf_data, shpToPlot = different_crs_shp),
                   "The CRS of 'shpToPlot' and 'pres' are not the same. Plot of shapefile skipped.")
  }
  
})


test_that("plotOutliers warning messages", {
  # Missing outlier columns
  sf_data <- create_test_data_plot()
  expect_warning(plotOutliers(pres = sf_data),
                 paste0("The 'out_spatial' or  'out_env' columns are not found ",
                        "in 'pres'. This is typically generated by the 'findOutliers'",
                        ", 'envOutliers' or 'spatialOutliers' functions."))
  if(requireNamespace("sf", quietly = TRUE)){
    # Shapefile and presence data with different CRS
    shp <- create_test_shape()
    different_crs_shp <- sf::st_transform(shp, 32617)
    sf_data_with_outliers <- create_test_data_plot(has_outliers = TRUE)
    expect_warning(plotOutliers(pres = sf_data_with_outliers, shpToPlot = different_crs_shp),
                   "The CRS of 'shpToPlot' and 'pres' are not the same. Plot of shapefile skipped.")
  }
})

test_that("plotOutliers output structure", {
  sf_data <- create_test_data_plot(has_outliers = TRUE)
  result <- plotOutliers(pres = sf_data)
  expect_invisible(invisible(result))
})
